### ISSUE TITLE
Components rendered with empty classes

### ISSUE THREAD

**Issue by tobice** [roylee0704/react-flexbox-grid#10]
This is my React code:

```html
<Grid>
  <Row>
     <Col md={12} lg={6}><h1>Hey!</h1></Col>
     <Col md={12} lg={6}>Ups</Col>
  </Row>
</Grid>
```
And this is output:

```html
<div class="" data-reactid=".0.1">
  <div class="" data-reactid=".0.1.0">
    <div class=" " data-reactid=".0.1.0.0"><h1 data-reactid=".0.1.0.0.0">Hey!</h1></div>
    <div class=" " data-reactid=".0.1.0.1">Ups</div>
  </div>
</div>
```

For some reason the classes are not filled (but notice the space).

This might be relevant. After I installed react-flexbox-grid, I got an error message (I'm using webpack):

```
ERROR in ./~/react-flexbox-grid/lib/components/Grid.js
Module not found: Error: Cannot resolve module 'classnames' in /home/tobik/scala/payola-viz/src/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Grid.js 9:18-39
```

I fixed it by adding `classnames` to my dependencies. After that I was able to build the package but it behaves the way described above.

My version is `0.9.2`.

**Comment by roylee0704** [comment]
Yes classnames is a required dependency. Let me check again what went wrong for the latest patch release.

**Comment by roylee0704** [comment]
have you forgotten to setup `style-loader` in your webpack config?

```js
  module: {
    loaders: [
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
      }
    ]
  }
```

**Comment by tobice** [comment]
Yes, I have forgotten to do that. Sorry. I set up my webpack config the same way as the [one](https://github.com/roylee0704/react-flexbox-grid/blob/master/doc/webpack.config.development.js) you use for generating docs but now I'm getting error `...is not a PostCSS plugin...` (lots of CSS is printed before that). I removed `postcss` from the loader chain which fixed the error and also the classes are finally set to the React output but corresponding CSS definitions are missing so it still doesn't work. I guess `postcss` was there for a reason...

The way I understand it is that random unique css classes are generated and they are both used in the JS and CSS definitions, right?

Is it possible to turn this feature off? This is kind of redundant at this moment for me and on top of that, I'm not sure I like having my config bloated with all those extra loaders active just to make CSS grid working. Plus I also use SASS in my app which means that unless I want the loaders to be shared for both your and my sass files I'd have to somehow separate it (right now I'm not an expert on this so I'd like to keep it simple).

**Comment by roylee0704** [comment]
Can you post your webpack confing here? :)

**Comment by tobice** [comment]
Okay, here you go:

```javascript
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var dir = __dirname + '/../../app/assets_webpack/appgen/javascripts';

module.exports = {
    entry: [
        'webpack-hot-middleware/client',
        dir + '/index.js'
    ],
    devtool: 'cheap-module-eval-source-map',
    output: {
        path: __dirname + "/../../target/web/public/main/javascripts/appgen/index.js",
        filename: "bundle.js",
        publicPath: "http://localhost:9090/build/"
    },
    plugins: [
        new ExtractTextPlugin('bundle.css', {allChunks: true}),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    resolve: {
        extensions: ['', '.js', '.json', '.scss']
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loaders: ['react-hot', 'babel'],
                exclude: /node_modules/
            },
            {
                test: /(\.scss|\.css)$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
            }
        ]
    }
};
```
This config is throwing me the `...is not a PostCSS plugin...` problem. Thank you :)

**Comment by heldr** [comment]
I believe **classnames** pkg could be a peerDependency with `*` wildcard instead.

It would emit warnings once react-flexbox-grid is installed.

What do you guys think?

**Comment by roylee0704** [comment]
@tobice , meanwhile try to `npm install postcss` :)

**Comment by tobice** [comment]
I do have `postcss` installed :)

**Comment by roylee0704** [comment]
ohh, @tobice okay :)

What about `postcss` configuration in webpack config?
```js
  postcss: [autoprefixer],
```

of these: 
```js

  module: {
    loaders: [
      {
        test: /(\.js|\.jsx)$/,
        exclude: /(node_modules)/,
        loader: 'babel'
      }, {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
      }, {
        test: /(\.md)$/,
        loader: 'html!highlight!markdown'
      }
    ]
  },
  postcss: [autoprefixer],

```

**Comment by roylee0704** [comment]
@heldr  aww wait, `classnames` module has already been added into the built library already :) So, `classnames` is not needed if you `npm install react-flexbox-grid`

**Comment by tobice** [comment]
@roylee0704 Sorry, still no luck. 

This is the [complete error message](http://pastebin.com/TSL8k1XV) that I get for every CSS/SCSS file which is built. And [these](http://pastebin.com/ZYCfdkSi) are my dependencies.

Btw. I had to add `classnames` to my dependencies to make it work. You must have changed the behavior in the past 24 hours or so.

**Comment by roylee0704** [comment]
@tobice That is weird, just checking: you do have require('autoprefixer') on top right? Im gonna run through again when im back to my machine.

And thanks for staying with me.

**Comment by tobice** [comment]
@roylee0704 If I didn't have the `require` there it would complain about that :) This is my current webpack config which throws the error above:

```javascript
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var autoprefixer = require('autoprefixer');

var dir = __dirname + '/../../app/assets_webpack/appgen/javascripts';

module.exports = {
  entry: [
    'webpack-hot-middleware/client',
    dir + '/index.js'
  ],
  devtool: 'cheap-module-eval-source-map',
  output: {
    path: __dirname + "/../../target/web/public/main/javascripts/appgen/index.js",
    filename: "bundle.js",
    publicPath: "http://localhost:9090/build/"
  },
  resolve: {
    extensions: ['', '.js', '.json', '.scss']
  },
  module: {
    loaders: [{
        test: /\.js$/,
        loaders: ['react-hot', 'babel'],
        exclude: /node_modules/
      }, {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
        // loader: 'style!css!sass'
      }]
  },
  postcss: [autoprefixer],
  plugins: [
    new ExtractTextPlugin('bundle.css', {allChunks: true}),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};
```

The thing is that I'm not entirely sure what's happening there. What should be for example passed to `new ExtractTextPlugin('...')`. Why is there `bundle.css`? As of now, I'm just using webpack dev server from the commandline. Another snippet from my `package.json`:

```javascript
  "scripts": {
    "appgen-dev": "./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./conf/webpack/appgen-dev.js --progress --colors --port 9090 --hot --inline",
    "appgen-build": "./node_modules/webpack/bin/webpack.js --config ./conf/webpack/appgen-dev.js --progress --colors"
  },
```

But this shouldn't matter...

**Comment by roylee0704** [comment]
@heldr  , @tobice  First I would like to apologise for the wrong statements that I have made in the past, you guys were right, we do need to explicitly:

1. `npm install flexboxgrid`
2. `npm install classnames`

And to attend that issue, I will make them into `peer-dependencies` on next release so that warnings will be prompted if these 2 dependencies are unmet.

Secondly, @tobice I have made an example repo #9 to use `react-flexbox-grid`, which you could find it here: https://github.com/roylee0704/react-flexbox-grid-example :)

**Comment by tobice** [comment]
Okay, mystery solved. I wasn't actually paying enough attention to what you were saying. I was missing the `postcss-loader` package. For some reason I mixed up `postcss` and `postcss-loader` and thought that having just `postcss` is enough. Considering the error message, it's kind of obvious now :D 

Thank you for you help and patience.

Nevertheless, our long thread kind of proves the point I mentioned earlier. Adding the grid to a new project should be simpler and shouldn't require that many changes in the project's webpack config. I think that it's safe to assume that most of the people with the intention to use your library (and with webpack) are already using CSS bundling, i.e. they already have active less or sass loader. Then it would make sense to have the required styles already precompiled into standard pure CSS and included in you npm package. I could just `@import` or `require` your CSS file into my project and existing CSS loaders would take care of that (any would work, sass, less or even pure css loader).

(I can see that the precompiled minified CSS is already available in the original `flexboxgrid` package.)

Those generated class names are cool but in my opinion this feature makes sense only for larger projects and therefore should be opt-in.

I'm not an expert on this so take this just as a suggestion.

**Comment by roylee0704** [comment]
@tobice, in fact that's a pretty good suggestion, actually @heldr had make a pull request on what you've described above, over here #7 :) I will make my time to merge this awesome pull-request. 

Glad that it works for you now, phew :)
