### ISSUE TITLE
How to use without webpack

### ISSUE THREAD

**Issue by KARTIK01** [roylee0704/react-flexbox-grid#100]
I am not using webpack in my project, 
instead using [facebooks create react app](https://github.com/facebookincubator/create-react-app)
its uses **react-scripts** instead of webpack.
So how can i use react-flexbox-gri.d. 
please reply ASAP.

**Comment by deltaidea** [comment]
If you'd search a bit yourself in the issues, you would find this: https://github.com/roylee0704/react-flexbox-grid/issues/55#issuecomment-285555262

**Comment by KARTIK01** [comment]
Thanks
