### ISSUE TITLE
issues with preset?

### ISSUE THREAD

**Issue by eduardoinnorway** [roylee0704/react-flexbox-grid#103]
I get,

resolve failed for "eslint-module-utils": Error: Cannot find module 'eslint-module-utils'
resolve failed for "caniuse-db": Error: Cannot find module 'caniuse-db'
resolve failed for "babel-runtime": Error: Cannot find module 'babel-runtime'

**Comment by deltaidea** [comment]
How do you reproduce this? Are you sure `react-flexbox-grid` is the reason?

**Comment by eduardoinnorway** [comment]
Well this issue came only after installing react-flexbox-grid. I will try again my luck on tomorrow. Coding very late, leads to unexpected misstakes some times :)

**Comment by silvenon** [comment]
This errors don't look like they' re related to react-flexbox-grid at all, so I'm closing this until we get more info and confirm that it is indeed related.
