### ISSUE TITLE
centered Grid

### ISSUE THREAD

**Issue by lsentkiewicz** [roylee0704/react-flexbox-grid#104]
What is the proper way to get a centered grid with max-width?

`<Grid />` it sets max-width, but doesn't center, and there is no padding.
`<Grid fluid />` full width with paddings

at http://flexboxgrid.com/ they added an extra `wrap` class.

![image](https://cloud.githubusercontent.com/assets/4478684/24494245/e3bb7c50-1531-11e7-9866-17e11daf0cdb.png)

I solved it by creating a custom global class, and I use `<Grid className="wrap"/>`, but I think it should be supported directly by the component.

Any thoughts?

**Comment by silvenon** [comment]
We should add it as a prop then, yes. I wonder why it's missing from their documentation. So this should only work for `<Grid fluid>` or also for `<Grid>`?

**Comment by lsentkiewicz** [comment]
Only for `<Grid>`

**Comment by silvenon** [comment]
`<Grid>` **does** center, [look](https://github.com/kristoferjoseph/flexboxgrid/blob/140537b370f7dcef1d357ac82344627a1e1a2107/dist/flexboxgrid.css#L3-L4).

react-flexbox-grid is meant to be strictly React bindings for flexboxgrid, not fix its shortcomings. `.wrap` is not a part of flexboxgrid, therefore should not be included.
