### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by davidep87** [roylee0704/react-flexbox-grid#106]
After a React update i get this message related to PropTypes deprecation.

Warning: **Accessing PropTypes via the main React package is deprecated**. 
Use the prop-types package from npm instead.

**Comment by silvenon** [comment]
Thanks for reporting! Frankly I'm unfamiliar with latest React updates/deprecations, which React version are you referring to?

**Comment by davidep87** [comment]
I'm running the version 15.5.3

**Comment by WillyPoteloin** [comment]
Same here ! React 15.5.4

**Comment by mastrauckas** [comment]
Facebook moved `PropTypes` from package `React` to `prop-types` starting from v15.5 as stated [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

**Comment by roylee0704** [comment]
#111  Should resolve this.
