### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by davidep87** [roylee0704/react-flexbox-grid#114]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Please check the file  /src/types.js

**Comment by mastrauckas** [comment]
I missed that on Pull Request #107.

**Comment by mastrauckas** [comment]
I put in a PR #115 to fix this issue.

**Comment by roylee0704** [comment]
I've released a patch with this fix ;)

**Comment by timmo001** [comment]
Ah nice one getting this fixed. Real annoyance, seems like many of the packages i'm using need this fix also
