### ISSUE TITLE
The "Holy Grail" in react-flexbox-grid

### ISSUE THREAD

**Issue by advance512** [roylee0704/react-flexbox-grid#116]
Hi there,

I'm trying to implement the ["Holy Grail" of Layout](https://philipwalton.github.io/solved-by-flexbox/demos/holy-grail/) using react-flexbox-grid. I can get the full width properly, but for some reason the main content/menu/ads-sidebar row does not take up the entirety of the screen.

Here is a very simple example of how to do this using pure CSS:
https://codepen.io/ryanseddon/pen/vnHJr

And another very complete example from a few months ago:
http://bl.ocks.org/jfsiii/5380802

Could any project developer give his input about this? 
I am certain an answer to this question will benefit many potential users of `react-flexbox-grid`.

**Comment by MarcoGrochowski** [comment]
I am also interested in this! I will let you know if I find out something ;).

**Comment by silvenon** [comment]
This project has the same limitations as [flexboxgrid](https://github.com/kristoferjoseph/flexboxgrid). It doesn't contain **all** Flexbox properties, especially `flex-direction` etc. It's meant for grids, not as a replacement for coding with Flexbox altogether.

So yes, currently the Holy Grail is not possible without adding some Flexbox properties yourself.
