### ISSUE TITLE
Support for React v16.0.0^

### ISSUE THREAD

**Issue by advance512** [roylee0704/react-flexbox-grid#117]
```
warning "react-flexbox-grid@1.1.2" has incorrect peer dependency "react@^0.14.3 || ^15.5.4".
```

**Comment by roylee0704** [comment]
@advance512  Do I also need to update devDependencies.react into v16.0.0 ?

**Comment by advance512** [comment]
@roylee0704:

IMHO:
`react@^0.14.3 || ^15.5.4 || ^16.0.0`

**Comment by roylee0704** [comment]
Sure :) I will do it once I'm home.

**Comment by roylee0704** [comment]
@advance512 It should be done ;)
