### ISSUE TITLE
Updated code published to npm repo?

### ISSUE THREAD

**Issue by zentuit** [roylee0704/react-flexbox-grid#118]
I see that the latest release is 1.1.3 however the latest in the npm repo is 1.0.2.

Release 1.1.3 has the updates for PropTypes that we want (so our tests stop spamming warning/error messages).

Any chance of a new published npm soon?

**Comment by roylee0704** [comment]
I thought I did, check again :)

**Comment by zentuit** [comment]
Whoops! I'm in the wrong repo!  It was `react-styled-flexboxgrid` that hasn't been updated!

Sorry about that.
