### ISSUE TITLE
Style is not being imported after v1.1.4

### ISSUE THREAD

**Issue by lhas** [roylee0704/react-flexbox-grid#129]
After the last release `v1.1.4`, on my project, the grid stopped to work. It looks like the classnames are different and don't contain any stylesheet for it. You can help me on this, please?
![image](https://user-images.githubusercontent.com/1396448/29084121-69a3d56c-7c41-11e7-885d-ecae9522ee36.png)

**Comment by lhas** [comment]
I fixed adding `import 'react-flexbox-grid/lib/index.css';`` to my `main.js` but not sure if this is the correct solution, specially because in `v1.1.3` it works.

**Comment by shan-du** [comment]
We had the same problem, our solution is to just fix the version to `1.1.3` for now

**Comment by roylee0704** [comment]
Sorry guys, kindly fix version to 1.1.3 until I figure out what's the issue.

**Comment by roylee0704** [comment]
in 1.1.4, I merged this: https://github.com/roylee0704/react-flexbox-grid/pull/126

**Comment by NicholasAsimov** [comment]
Same problem here, 1.1.4 broke styles.

**Comment by alevor657** [comment]
Same here, having troubles.

**Comment by Taylor123** [comment]
Any update on this? I just ran into issues with v1.1.4

I'm not using any bundler at the moment. Could that be causing an issue on my end?

**Comment by danny-andrews** [comment]
This was my fault, folks. Sorry for the inconvenience. I have a fix up [here](https://github.com/roylee0704/react-flexbox-grid/pull/130).

**Comment by danny-andrews** [comment]
If someone could try out this build https://github.com/roylee0704/react-flexbox-grid/pull/130 and make sure it fixes this, that would be greatly appreciated. It works for me, but would like to verify it fixes your guys' use-cases as well.

**Comment by lhas** [comment]
Thanks, @danny-andrews . Actually i'm using the `v1.1.3` build. But monday i will try this new build. See ya!

**Comment by rpedroni** [comment]
Hey guys, any updates on this?

**Comment by danielkrich** [comment]
same !!! spent hours to figure out what's wrong with my project -.-
the `import 'react-flexbox-grid/lib/index.css'` fixed it for me for now...

**Comment by rajiff** [comment]
Hi, is there any plan to fix this?

**Comment by danny-andrews** [comment]
I have a PR to fix it. Just waiting on one of the maintainers to ok it. @roylee0704 @silvenon.

**Comment by danny-andrews** [comment]
Can someone here give this a go and verify that it fixes your issues? The fix is on master. Note: you will have to run `yarn compile` in `node_modules/react-flexbox-grid`.

**Comment by roylee0704** [comment]
@rajiff @danielkrich @rpedroni @lhas It should be fixed under release v1.1.5
