### ISSUE TITLE
Switching to flexboxgrid2

### ISSUE THREAD

**Issue by Kamahl19** [roylee0704/react-flexbox-grid#137]
Hi, 

since the original flexboxgrid seems abandoned and has pretty major bugs (like this one https://github.com/kristoferjoseph/flexboxgrid/issues/144), I think it might be better to switch to the forked and actively developed https://github.com/evgenyrodionov/flexboxgrid2 . It includes fix for that Horizontal scrollbar bug, also some other fixes, a new XL viewport and .hidden- classes for hiding columns on different viewports. What are your thoughts?

**Comment by roylee0704** [comment]
Thanks for the PR! @Kamahl19 I've merged and released :)
