### ISSUE TITLE
2.1.1 fails when building using Create React App

### ISSUE THREAD

**Issue by mikaelgson** [roylee0704/react-flexbox-grid#152]
The latest release 2.1.1 fails when running `npm run build` using Create React App.
Getting: 
>Failed to minify the code from this file: 
./node_modules/react-flexbox-grid/lib/createProps.js:4 

Im guessing https://github.com/roylee0704/react-flexbox-grid/pull/148 could be the culprit here.

If i downgrade to 2.1.0 it works as expected.

**Comment by roylee0704** [comment]
It's fixed under release `v2.1.2`, due to missing value: "env" in babelrc  :)

Thanks @mikaelgson !

**Comment by mikaelgson** [comment]
@roylee0704 Great! :+1:
