### ISSUE TITLE
dist build in v2.1.1 no longer includes react-flexbox-grid.css

### ISSUE THREAD

**Issue by ayliao** [roylee0704/react-flexbox-grid#153]
Hi there!

I noticed that in v2.1.1 there is no longer a **react-flexbox-grid.css** file in the dist build. I was curious if this was intentional?

Thanks in advance!

**Comment by roylee0704** [comment]
It's fixed under release `v2.1.2`, due to missing value: "env" in babelrc  :)

**Comment by ayliao** [comment]
Awesome! Thank you for the quick response :D
