### ISSUE TITLE
There's no Container component

### ISSUE THREAD

**Issue by derekstavis** [roylee0704/react-flexbox-grid#16]
Hi. I was following the README when I stumbled upon this code example:

```javascript
import React from `react`;
import {Container} from `react-flexbox-grid/lib/index`;

React.render(<Container />, document.querySelector('#main'));
```

As far I've looked in the code, there isn't a `Container` component.

Probably this is a typo which should be corrected to `Grid`.

**Comment by roylee0704** [comment]
ah, nice catch! yes you are right, let me fix it now.

**Comment by roylee0704** [comment]
fixed at latest commit :)
