### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ../style in /react-flexbox-grid/lib/components

### ISSUE THREAD

**Issue by shilpan** [roylee0704/react-flexbox-grid#17]
Changing `../style` to `../style.scss` resolved the issue

**Comment by maxkrieger** [comment]
Is there a better solution?

**Comment by yelmu** [comment]
I have encountered this error:

`Browserify Error { [Error: Cannot find module '../style' from '\node_modules\react-flexbox-grid\lib\components']`

**Comment by listepo** [comment]
+1

**Comment by heldr** [comment]
Getting the same error, gonna check why :tea:

**Comment by heldr** [comment]
@roylee0704 
For some unknown reason the npm task **prepublish** didn't run and the compiled version in **/lib** doesn't follow **/src** changes.

**Comment by listepo** [comment]
ping

**Comment by silvenon** [comment]
I believe adding `.scss` to [`resolve.extensions`](http://webpack.github.io/docs/configuration.html#resolve-extensions) should work.

**Comment by heldr** [comment]
@silvenon Recently we removed `style.scss` file in order to include flexbox-grid right in **require()** hook, and then remove sass as main dependency.

**Comment by silvenon** [comment]
Yes, there's no reason need for Sass here, I'm not sure why it's a dependency.

**Comment by listepo** [comment]
@silvenon thanks :+1:

**Comment by heldr** [comment]
@silvenon @listepo 
Look the style import
https://github.com/roylee0704/react-flexbox-grid/blob/master/src/components/Col.js
https://github.com/roylee0704/react-flexbox-grid/blob/master/src/components/Grid.js
https://github.com/roylee0704/react-flexbox-grid/blob/master/src/components/Row.js

It's just a matter of building and publishing it!

**Comment by MarioJerkovicDickeys** [comment]
Waiting the new publish

**Comment by jachinte** [comment]
:+1:

**Comment by JasonWeise** [comment]
Do we know when the new build will be available. Having this exact issue as well.

**Comment by heldr** [comment]
Workaround for Babel users, on your package.json:
```json
{
  "scripts": {
    "postinstall": "babel -d node_modules/react-flexbox-grid/lib node_modules/react-flexbox-grid/src"
  }
}
```

It requires [babel-preset-es2015-loose](http://npm.im/babel-preset-es2015-loose).

**Comment by v3rron** [comment]
Working with Meteor/React and ES6 and after adding the `import {Container} from 'react-flexbox-grid/lib/index';` having this issue:
````
Uncaught Error: Cannot find module '../style'
````

**Comment by sanandnarayan** [comment]
+1

**Comment by roylee0704** [comment]
I'm really really sorry for the delayed, just recovered from a serious sickness. @heldr  Thanks for the email.

**Comment by roylee0704** [comment]
just done `npm publish` with the latest fixes. :)

**Comment by shilpan** [comment]
hope you're feeling better thanks for this!

**Comment by silvenon** [comment]
Wohoo :+1:

**Comment by sanderdatema** [comment]
@v3rron Did you get it working eventually?

**Comment by v3rron** [comment]
@sanandnarayan I didn't have a chance to test the last version. Ended up installing nemo64:bootstrap meteor package. Since I use material-ui on top of bootstrap it works good for my case.
