### ISSUE TITLE
Not loading style.scss

### ISSUE THREAD

**Issue by delaneyj** [roylee0704/react-flexbox-grid#2]
Not sure what's going on but trying to use this lib and have npm installed flexboxgrid & react-flexbox-grid.

```
ERROR in ./~/react-flexbox-grid/lib/components/Grid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../style in C:\tradefloor\code\fuck2\node_modules\react-flexbox-grid\lib\components
 @ ./~/react-flexbox-grid/lib/components/Grid.js 21:13-32

ERROR in ./~/react-flexbox-grid/lib/components/Row.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../style in C:\tradefloor\code\fuck2\node_modules\react-flexbox-grid\lib\components
 @ ./~/react-flexbox-grid/lib/components/Row.js 21:13-32

ERROR in ./~/react-flexbox-grid/lib/components/Col.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../style in C:\tradefloor\code\fuck2\node_modules\react-flexbox-grid\lib\components
 @ ./~/react-flexbox-grid/lib/components/Col.js 15:13-32
```

my webpack config has 
```
{
    test: /\.(scss|css)$/,
    loaders: ["style", "css", "sass"]
},
```

And other stuff like normalize/material-icon's css/images are pulling in fine.  any ideas?

**Comment by roylee0704** [comment]
hmm, could you show me your webpack?

**Comment by roylee0704** [comment]
For how-to-use my library in webpack flow, you could also reference to my [/doc](https://github.com/roylee0704/react-flexbox-grid/tree/master/doc) directory.

**Comment by lukkuz** [comment]
@delaneyj I have run into similar problem. In my case I had to change my webpack config in order to be able to require .scss files without specifying extension.

Try adding something like this:
```javascript
resolve: {
    // you can now require('style') instead of require('style.scss')
    extensions: ['', '.js', '.json', '.scss'] 
  }
```

**Comment by roylee0704** [comment]
Thanks @lukkuz  ;) @delaneyj still having issues?

**Comment by delaneyj** [comment]
Sorry, got pulled off on other things, hopefully that will resolve it.

**Comment by nainy** [comment]
Sorry to revive such an ancient issue, but I'm having a very similar problem:

> ERROR in ./~/react-flexbox-grid/lib/components/Grid.js
Module not found: Error: Cannot resolve module 'style' in /var/www/subtrack/web/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Grid.js 18:19-41

> ERROR in ./~/react-flexbox-grid/lib/components/Col.js
Module not found: Error: Cannot resolve module 'style' in /var/www/subtrack/web/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Col.js 14:19-41

> ERROR in ./~/react-flexbox-grid/lib/components/Row.js
Module not found: Error: Cannot resolve module 'style' in /var/www/subtrack/web/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Row.js 18:19-41

My webpack config:

`{
    context: __dirname,
    entry: [
        'webpack-hot-middleware/client',
        './src'
    ],
    devtool: 'source-map',
    output: {
        path: './public',
        publicPath: '/',
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['', '.jsx', '.scss', '.js', '.json'],
        modulesDirectories: [
            'node_modules'
        ]
    },
    module: {
        loaders: [
            {
                test: /(\.scss|\.css)$/,
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
            },
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react', 'stage-0']
                }
            }
        ]
    },
    postcss: [autoprefixer],
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new webpack.optimize.OccurenceOrderPlugin()
    ]
}`

Probably missing something, but can't put my thumb on it yet.
