### ISSUE TITLE
className always empty

### ISSUE THREAD

**Issue by rkmax** [roylee0704/react-flexbox-grid#21]
Always I'm getting class Name empty so the layout doesn't work. any advice?. please ask me for further info is need, because I'm new with React I dont know which info share

![captura de pantalla de 2016-02-23 12-01-46](https://cloud.githubusercontent.com/assets/395707/13259359/f8b2d926-da24-11e5-8288-c2aca8f151dd.png)

I'm very curious because I have a simple component. I want the text *Hello from here* appear in the left and the form on right side

```js
let layout = {
  xs: 6,
  sm: 6,
  md: 6,
  lg: 6
}
```

```xml
<Grid fluid>
  <Row>
    <Col {...layout}>
      <p>Hello from here</p>
    </Col>
    <Col {...layout}>
      <Paper>
        <Row>
          <TextField
            hintText='Name'
            floatingLabelText='Name'/>
        </Row>

        <Row>
          <TextField
            hintText='Email'
            floatingLabelText='Email'
            type='email'/>
        </Row>
        <Row>
          <TextField
            hintText='Password'
            floatingLabelText='Password'
            type='password'/>
        </Row>
        <Row>
          <TextField
            hintText='Re Enter Password'
            floatingLabelText='Re Enter Password'
            type='password'/>
        </Row>
        <Row>
          <a href='#'>Already have an account? Sign in</a>
        </Row>
        <Row>
          <RaisedButton label='Submit' primary/>
        </Row>
      </Paper>
    </Col>
  </Row>
</Grid>
```

**Comment by leandroz** [comment]
I have the same issue and is related on how webpack is treating flexboxgrid. It should transform it into a css module.

**Comment by lawrence0819** [comment]
After update version form 0.9.4 to 0.9.5, all class name always empty.

**Comment by CoveTechnologyAus** [comment]
I am using Meteor with React and I have the same issue, classnames are always empty since installing 0.9.5.

**Comment by e-karma** [comment]
After fighting through webpack configs for 3 hours, I just now encountered... the same issue.  :(

**Comment by leandroz** [comment]
The problem is that this library depends on treating flexboxgrid dependency as a css-module. So you need to process it as css-module with webpack.

**Comment by e-karma** [comment]
@leandroz Thanks for the heads up!! Do you know the webpack code that works?

**Comment by bhoomit** [comment]
Same issue with me. 

```

var _flexboxgrid = require('flexboxgrid');
console.log(_flexboxgrid);

Output:
Object {}

```
prints empty object

**Comment by leandroz** [comment]
I am using https://github.com/davezuko/react-redux-starter-kit
Check the webpack config file, there is a place to add third party modules that need to be treated as css module.
Hope that helps!

Leandro Zubrezki

**Comment by Marmelatze** [comment]
Thanks @leandroz for pointing this out.

Adding ?modules to the loader fixed it for me:
```js
{
    test: /\.css/,
    loader: "style!css?modules"
},
```

**Comment by dubvfan87** [comment]
Do you know how I would add that using meteor webpack and their webpack.json file? Is webpack.json only a thing with the meteor webpack page or is that a pretty standard thing? Most examples I have seen use a webpack.js. My current webpack.json looks like this, and I can't add that block to my webpack.json file because of the regex.

`{
	"root": "src",
	"devServer": {
		"host": "localhost"
	},
	"css": {
		"module": true
	},
	"sass": {
		"includePaths": ["./node_modules"]
	},
	"css": {
		"includePaths": ["./node_modules"]
	}
}`

**Comment by roylee0704** [comment]
@leandroz and @Marmelatze , thanks for the solution! Anyhow do you guys have any ideas on how to prevent this?

**Comment by rkmax** [comment]
there's some way to print to console a warning if it's not processed as a CSS module

**Comment by roylee0704** [comment]
@rkmax Do you mind to help? :)

**Comment by rkmax** [comment]
I'm pretty new with webpack but I'll try figure out how to do it

**Comment by roylee0704** [comment]
Sure! Appreciate on that, meanwhile, I have added an info to prevent `Empty ClassName Issue` on README, I hope it is sufficient, but if it is confusing, let me know and I will try to enhance it.

**Comment by bhoomit** [comment]
@leandroz I was using the same boilerplate. And made it work the same way you did. Thanks anyway :)

**Comment by anhhh11** [comment]
Don't know why but code on `basic-webpack-configuration` not work :| , I must use the following:
```
{test: /\.css$/, loader: 'style!css?modules', include: path.resolve(__dirname, 'node_modules', 'flexboxgrid')},
{test: /\.css$/, loader: 'style!css', exclude: path.resolve(__dirname, 'node_modules', 'flexboxgrid')},
```

**Comment by gazzer82** [comment]
Ok, i really can't get this to work, here is my loaders config, seems to be correct to me, but i have the same issue with no class names?

```
module: {
    loaders:[
      //JSX
      {
        test: /\.jsx$/,
        exclude: /(node_modules)/,
        loaders: ['react-hot','babel']
      },
      //JS
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loaders: ['react-hot','babel']
      },
      //Load flexgrid
      {
        test: /(\.scss|\.css)$/,
        loader: 'style!css?modules!sass',
        include: __dirname + './node_modules/react-flexbox-grid',
        exclude: /(node_modules)/
      },
      //SCSS
      {
        test: /\.scss$/,
        exclude: /(node_modules)/,
        loader: 'style!css!sass'
      },
      //CSS
      { test: /\.css$/,
        loader: "style-loader!css-loader",
        exclude: __dirname + './node_modules/react-flexbox-grid',
      },
      //Fonts
      {
      test: /\.(woff|woff2)$/,
        loader: "url?limit=10000&mimetype=application/font-woff"
      },
      {
      test: /\.ttf$/,
        loader: "url?limit=10000&mimetype=application/octet-stream"
      },
      {
      test: /\.eot$/,
        loader: "file"
      },
      //Images
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loader: "url?limit=25000"
      }

    ]
  },
```

**Comment by roylee0704** [comment]
Good day @gazzer82! :)

Are you using any specific boilerplate? Do you mind to paste the entire webpack config here? :)

**Comment by silvenon** [comment]
@gazzer82 you should create paths using the [path](https://nodejs.org/dist/latest-v4.x/docs/api/path.html) module:

* `__dirname + './foo'` = `/Users/user/project./foo` :x: 
* `path.join(__dirname, 'foo')` = `/Users/user/project/foo` :white_check_mark:

**Comment by silvenon** [comment]
@gazzer82 can you please apply the updates in #27? You should now target `flexboxgrid` in your configuration, not `react-flexbox-grid`.

**Comment by TomPeak** [comment]
I am using the react incubator, could it work?, no webpack…
Classes are empty.

**Comment by superchangme** [comment]
![image](https://cloud.githubusercontent.com/assets/7008154/19589793/ea4827e4-97a0-11e6-89a2-332d81ef49ba.png)
This is my css module loader config
webpackConfig.module.loaders.push({
   test: /\.css$/,
   loader: 'style!css?modules',
   include: /flexboxgrid/
})
Clever Boy you will get it!
