### ISSUE TITLE
Updated Installation Docs Available?

### ISSUE THREAD

**Issue by e-karma** [roylee0704/react-flexbox-grid#24]
I've been stuck for a couple hours facing these 2 errors a few times each..

Cannot resolve module 'flexboxgrid' 13:19-41
Cannot resolve module 'classnames' 9:18-39

Your 'example' works but Im trying to integrate to an existing project where i'm less inclined to shake the tree for a grid.  That said, I really would love to give it a spin!  

Its a webpack project working independently and with minimal plugins.  I added only the code listed on your README. 

Thanks!

**Comment by roylee0704** [comment]
Oh, that's the two peerDependencies you've got to resolve before using `react-flexbox-grid`.  Sure I should have been make it explicit on README. Thanks for the issue :+1: 

Besides, it also has to work hand-in-hand with the setup of webpack. Am not sure if you need info on this integration part? :)

**Comment by e-karma** [comment]
Hi @roylee0704 , I successfully got the Library to load without error, but thats where the fun stopped.  From the other issue, you can see myself as well as a few others need guidance / a fix for the "Empty Classes" we experience.  All the DOM generated displays blank as of 0.9.5.  Do you know how to fix?

**Comment by bhoomit** [comment]
@e-karma found any resolution?

**Comment by e-karma** [comment]
@bhoomit nope, awaiting word from @roylee0704 about a fix.  My short-term recommendation would be just learn Flexbox.  Its already such an abstraction.  https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by bhoomit** [comment]
@e-karma ohhh, cool. Thanks!

**Comment by dubvfan87** [comment]
Migrating my meteor/mantra project to webpack allowed this to work correctly for me.

**Comment by roylee0704** [comment]
Grettings @e-karma , @bhoomit,
  
It is necessarily to append `?modules` on css loader,

```js
{
    test: /\.css/,
    loader: "style!css?modules"
},
```

Does this help solving your problem?

**Comment by bhoomit** [comment]
I am using https://github.com/davezuko/react-redux-starter-kit
Check the webpack config file, there is a place to add third party modules that need to be treated as css module.

I think it works the same way you suggested. Thanks :)

**Comment by roylee0704** [comment]
@bhoomit  Good to hear that! ;)

Anyway could you paste your webpack config here so that in future people could refer from it? :) At the same time, I will consolidate those working configs to wiki as well.

**Comment by bhoomit** [comment]
@roylee0704 I'm using this https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js webpack config. 

With 

Line 153:
```
const PATHS_TO_TREAT_AS_CSS_MODULES = [
  'react-flexbox-grid'
]
```

Need to see how it exactly works.

**Comment by silvenon** [comment]
Put `flexboxgrid` instead of `react-flexbox-grid`.

**Comment by roylee0704** [comment]
contrib to doc: react-redux-starter-kit: #26

**Comment by kyen99** [comment]
In case it helps anyone, to add react-flexbox-grid to the starter kit exclude /flexboxgrid/ from the  existing css and scss loaders and add a new loader for css?modules in webpack.config.js.

```
webpackConfig.module.loaders.push({
  test: /\.scss$/,
  exclude: /flexboxgrid/,          <---- added
  loaders: [
    'style',
    BASE_CSS_LOADER,
    'postcss',
    'sass?sourceMap'
  ]
})
webpackConfig.module.loaders.push({
  test: /\.css$/,
  exclude: /flexboxgrid/,          <---- added
  loaders: [
    'style',
    BASE_CSS_LOADER,
    'postcss'
  ]
})

/* This section is new */
webpackConfig.module.loaders.push({
  test: /\.css$/,
  include: /flexboxgrid/,
  loader: 'style!css?modules'
})
```

**Comment by silvenon** [comment]
It seems to me that this has been resolved. The instructions in our docs explain the CSS Modules setup, [which is now optional](https://github.com/roylee0704/react-flexbox-grid/releases/tag/v1.0.0). These issues arise because some boilerplates have complex webpack setups and sometimes users don't understand them very clearly.

Let me know if this is still an issue.
