### ISSUE TITLE
Not compatible system? skipping optional dependency?

### ISSUE THREAD

**Issue by RaulTsc** [roylee0704/react-flexbox-grid#3]
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN optional Skipping failed optional dependency /gulp-nodemon/nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but none was installed.
npm WARN react-flexbox-grid@0.8.3 requires a peer of flexboxgrid@^6.3.0 but none was installed.
npm WARN torrent-video@0.0.0 No license field.

This is the log after doing ` npm install react-flexbox-grid ` . Also my babel keeps throwing ` Cannot find module X in lib/components ` compile errors. Am I missing something?

Thanks

**Comment by roylee0704** [comment]
what is your npm version?

**Comment by RaulTsc** [comment]
3.5.2

**Comment by roylee0704** [comment]
Oh, I'm actually using 4.5.5. Probably upgrade it would solve the issue?

**Comment by roylee0704** [comment]
Earlier on I mistakenly posted node version as opposed to npm version, sorry about that.
Currently I'm using npm v3.5.3, node v5.4.0

By the way, I have merged PR #5 from @heldr and updated to react-flexbox-grid v0.9.x maybe you would want to reinstall and try again? :)

**Comment by roylee0704** [comment]
Hi @RaulTsc I'm sorry for the late response, to address that issue, I have made an example repo #9 just to show how to use react-flexbox-grid in webpack, sass, and css-modules.

You may pull from here: https://github.com/roylee0704/react-flexbox-grid-example :)

**Comment by RaulTsc** [comment]
Thanks. :+1: I'll take a look sometime. Kind of busy atm

**Comment by roylee0704** [comment]
Alright, feel free to reopen this issue if you still encounter any problem. :)
