### ISSUE TITLE
Add react-flexbox-grid into meteor

### ISSUE THREAD

**Issue by lawrentiy** [roylee0704/react-flexbox-grid#32]
Hi, guys!
I have meteor 1.3.2 app with React.
I tried to add react-flexbox-grid. 

A. As a meteor package 
meteor add jimmiebtlr:react-flexbox-grid

app.jsx:
```
import RFBG from 'meteor/jimmiebtlr:react-flexbox-grid'
console.log(RFBG);
```

B. As a npm packages 
meteor npm install classnames flexboxgrid react-flexbox-grid
app.jsx:
```
import RFBG from 'react-flexbox-grid/lib/index';
console.log(RFBG);
```
console error:

> /app/node_modules/flexboxgrid/dist/flexboxgrid.css:1
> W20160525-22:39:32.291(3)? (STDERR) (function (exports, require, module, __filename, __dirname) { .container-fluid
> W20160525-22:39:32.291(3)? (STDERR)                                                               ^
> W20160525-22:39:32.296(3)? (STDERR) SyntaxError: Unexpected token .
> W20160525-22:39:32.296(3)? (STDERR)     at Module._compile (module.js:439:25)
> W20160525-22:39:32.296(3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
> W20160525-22:39:32.296(3)? (STDERR)     at Module.load (module.js:356:32)
> W20160525-22:39:32.297(3)? (STDERR)     at Function.Module._load (module.js:312:12)
> W20160525-22:39:32.297(3)? (STDERR)     at Module.require (module.js:364:17)
> W20160525-22:39:32.297(3)? (STDERR)     at require (module.js:380:17)
> W20160525-22:39:32.297(3)? (STDERR)     at Object.<anonymous> (/app/node_modules/react-flexbox-grid/lib/components/Grid.js:13:20)
> W20160525-22:39:32.297(3)? (STDERR)     at Module._compile (module.js:456:26)
> W20160525-22:39:32.297(3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
> W20160525-22:39:32.297(3)? (STDERR)     at Module.load (module.js:356:32)
> 

In both cases RFBG - undefined.

What I`he done wrong?

Thanx!

**Comment by rcarter** [comment]
For a meteor app, try importing like this:

`import {Grid, Row, Col} from 'meteor/jimmiebtlr:react-flexbox-grid'`

**Comment by lawrentiy** [comment]
Thnx! 
It was my fault.
I`he add package into application packages file
and use it from another package, in PACKAGE_DIRS folder.

**Comment by tzapu** [comment]
i m having some trouble with using this in meteor as well.
i ve installed from npm directly, import works fine, but classes come empty.
since i m using meteor i don t have a webpack config or similar that i am aware... what should i do?
sorry for the noobness and thanks for a great grid

**Comment by silvenon** [comment]
@tzapu subscribe to #60 to get updates about this. CSS Modules seem to be webpack-only thing so far, but it would be great if we could gracefully fall back to regular classes in case CSS Modules aren't enabled.
