### ISSUE TITLE
Question: How does this compare to "kristoferjoseph/flexboxgrid" ?

### ISSUE THREAD

**Issue by boustanihani** [roylee0704/react-flexbox-grid#35]
How does this project compare to: https://github.com/kristoferjoseph/flexboxgrid

The sites seem to be identical!!
- http://roylee0704.github.io/react-flexbox-grid/
- http://flexboxgrid.com/

**Comment by silvenon** [comment]
The 1st paragraph of the readme explains it pretty well:

> React-Flexbox-Grid is a set of React components that implement flexboxgrid.css. It's built on top of some the trendiest proposals like CSS Modules (written in SASS), Webpack and ES6. The library harmoniously integrates with your Webpack workflow and it's easily customizable and very flexible.

Let me know if it's still unclear 😉

**Comment by boustanihani** [comment]
Thanks
