### ISSUE TITLE
Version 1.0 ideas

### ISSUE THREAD

**Issue by heldr** [roylee0704/react-flexbox-grid#36]
Just having some ideas for a possible major release (also checking before to start PR stuffs)
1. Stateless functions instead of class components (since React 0.14) [Read more](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions)
2. A [HOC (Higher Order Component)](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.kodk38yyt) function **withGrid** like React-router [**withRouter**](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md), an alternative to support/inject grid props instead of nesting.
3. No peerDependencies required but flexboxgrid and react.
4. Universal module(ES6, CJS, AMD, window global)

What do you think? More suggestions?
@roylee0704 @silvenon @ankitduseja

**Comment by roylee0704** [comment]
@heldr  sure, I'm good with those items to take us to major release.

**Comment by roylee0704** [comment]
https://waffle.io/roylee0704/react-flexbox-grid/join

**Comment by heldr** [comment]
Nice! I will check a free time next week to start doing it

**Comment by roylee0704** [comment]
Let's close this for now. Till the time when we have time to work on this, we'll reopen this. :)
