### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by nadeemja** [roylee0704/react-flexbox-grid#39]
Hi,

Followed your examples.

But it does not work.

import React from 'react';
import { Grid, Row, Col } from 'react-flexbox-grid/lib/index';

    import React from 'react';
    import { Grid, Row, Col } from 'react-flexbox-grid/lib/index';

    const Home = () => (
      <div>
        <Grid>
          <Row>
            <Col xs={6} md={3}>Hello, world!</Col>
            <Col xs={6} md={3}>Hello, world!</Col>
            <Col xs={6} md={3}>Hello, world!</Col>
            <Col xs={6} md={3}>Hello, world!</Col>
          </Row>
        </Grid>
      </div>
    );

    export default Home;

This just prints out empty divs without any class attributes.

**Comment by nadeemja** [comment]
This seems to be caused by not using wepack

**Comment by smeijer** [comment]
So what you're saying? We cannot use this library without using webpack?

**Comment by silvenon** [comment]
@smeijer currently, yes.
