### ISSUE TITLE
BUG: Centering does not work

### ISSUE THREAD

**Issue by nadeemja** [roylee0704/react-flexbox-grid#41]
Hi,

I copy/pasted the lines below, but they did not have the desired effect.

    <Row>
      <Col xs={12}>
        <Row center="sm">
          <Col xs={2}>
            hei
          </Col>
        </Row>
      </Col>
    </Row>
    
Let me know what information I need to provide to help you help me.
Thanks.

**Comment by silvenon** [comment]
Your example works for me. What happened in your case and what did you expect to happen?

<img width="789" alt="screen shot 2016-07-16 at 13 19 42" src="https://cloud.githubusercontent.com/assets/471278/16894486/eeba43b0-4b57-11e6-9aa3-7eb69353930b.png">

**Comment by nadeemja** [comment]
Hello,

Apologies for not closing this. 
I believe I was using this with meteor, which left all the classes empty. 

Thank you for paying attention to this and attempting to help.
I really appreciate it, and will be more thoughtful in the future.
