### ISSUE TITLE
Avoid passing unsupported props to underlying DOM elements

### ISSUE THREAD

**Issue by tobice** [roylee0704/react-flexbox-grid#44]
After updating to React 15.2, react-flexbox-grid is throwing lots of similar warnings:

```
Warning: Unknown props `lg`, `lgOffset` on <div> tag. Remove these props from the element
```

I just checked the current GitHub code and this seems to be fixed. But the changes hasn't been published to npm yet...

**Comment by NeXTs** [comment]
looking forward publishing :+1:

**Comment by heldr** [comment]
Please follow #38 in order to know when its published

**Comment by heldr** [comment]
Please follow #38 in order to check when its published

**Comment by roylee0704** [comment]
@tobice, it's been published now! :)
