### ISSUE TITLE
v0.10.1 no lib files

### ISSUE THREAD

**Issue by beckend** [roylee0704/react-flexbox-grid#48]
Installing through `npm@3.10.5`.
v0.10.1 has no lib folder built.

V0.9.6:
```javascript
node_modules/react-flexbox-grid/lib/components
node_modules/react-flexbox-grid/lib/components/Col.js
node_modules/react-flexbox-grid/lib/components/Grid.js
node_modules/react-flexbox-grid/lib/components/Row.js
node_modules/react-flexbox-grid/lib/index.js
```

**Comment by roylee0704** [comment]
#46

**Comment by skeet** [comment]
The temp solution isn't any good when needing to deploy.

Can you confirm you're looking for a fix for the missing lib folder?

**Comment by smeijer** [comment]
A fix would be most welcome.

**Comment by roylee0704** [comment]
@skeet @smeijer  Absolutely, the reason for temp solution because my machine was sent for service. However I just got back my machine, will look into it and fix it asap. :) Sorry for the wait. In the meantime, any help or pr will be great too :)

**Comment by roylee0704** [comment]
Bug fixed in new version :)

**Comment by skeet** [comment]
@roylee0704 Thanks! Appreciate it.

**Comment by smeijer** [comment]
No worries.  I read trough the issues, and you're always pretty quick with patches. 

Thanks for the update.
