### ISSUE TITLE
Can we remove `babel-polyfill` dependency?

### ISSUE THREAD

**Issue by alexilyaev** [roylee0704/react-flexbox-grid#51]
Hey guys, I was wondering which parts of the code depend on `babel-polyfill`?

Very similar to https://github.com/roylee0704/react-flexbox-grid/issues/49 request.
I would very much like not to include `babel-polyfill` in my project, since I don't need it.

I'm willing to help out, just let me know where are we using something that `babel-polyfill` covers?

**Comment by Jbarget** [comment]
👍
