### ISSUE TITLE
How to add custom class to Col/Row/Container

### ISSUE THREAD

**Issue by pavel06081991** [roylee0704/react-flexbox-grid#54]
I want to add some additional styles to tag which is Col or Row or Container but it seems there are not opportunity to pass my custom css class to these components. It would be great to add this functionality:

```
this.myCustomCssClass = 'abc';

<Col xs={6} md={3} customClass={this.myCustomCssClass}>Hello, world!</Col>
```

**Comment by Nathan-Schwartz** [comment]
This is possible with the standard className property: `<Col className={customClass}> </Col>`
