### ISSUE TITLE
Installation steps with  Create React App tool. 

### ISSUE THREAD

**Issue by t00f** [roylee0704/react-flexbox-grid#55]
Hi,

I would need some help to set up `react-flexbox-grid` using the latest [Create React Tool](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html)

The webpack configuration is an internal dependancy.
How would you set up your environment ?

**Comment by JacopKane** [comment]
@t00f If there isn't any other way than configuring webpack, short answer is you need to eject your app with  ```npm run eject```command for modifying your webpack configuration (see the docs of create-react-app). It will move all configurations to your root folder. However after this you can't return back to the your current internal dependency structure again.

**Comment by lucafaggianelli** [comment]
Yes it would be nice to add out-of-the-box support with create-react-app tool. Currently it seems that CSS is not loaded and CSS classes are not added to HTML elements, do you think there's a trick to let it work without running `npm run eject`?

**Comment by silvenon** [comment]
Unfortunately CRA doesn't let you configure css-loader to enable CSS Modules, which this module currently depends on. We should make this module fall back to regular CSS classes in case CSS Modules aren't enabled. Please subscribe to #60 for updates about this.

**Comment by deltaidea** [comment]
**For other people coming from Google:** you can use `react-flexbox-grid` with `create-react-app` right now.

Manual Webpack configuration is no longer mandatory, but this is not yet released. Until 1.0.0 hits npm, you can get this package directly from GitHub.

- Add this to `package.json`: `"react-flexbox-grid": "https://github.com/roylee0704/react-flexbox-grid.git#master"`
- Add this to `scripts`: `"postinstall": "(cd node_modules/react-flexbox-grid && npm install && npm run build)"`

This will download source code of this package and build it for you. The only downside is that it installs dev dependencies of this package for building, which takes time. No extra action is required, this will work with the standard workflow of `yarn/npm install` and `yarn/npm start`.

WARNING: This installs the package from `master` which might not be stable enough for production.
Watch this repo for releases and revert back to `"react-flexbox-grid": "^1.0.0"` once it's ready.

**Comment by silvenon** [comment]
`master` should be ok. The release date is unfortunately out of my hands, but I've completed a draft of release notes. I know that @roylee0704 has been sick previously, but he reacted to my tweet recently, so he's alive ❤️ hopefully we'll have a release soon.

**Comment by WeeJeWel** [comment]
Unfortunately it seems that when I'm installing this no css styles are being loaded, but classes are added.

![screen shot 2017-08-14 at 21 09 39](https://user-images.githubusercontent.com/319873/29287209-fa89f8d4-8134-11e7-95e3-2720713634c2.png)

**Comment by breakingthebuild** [comment]
I am seeing the same thing as @WeeJeWel. Classes are added but no styles. Any updates?

**Comment by gallan** [comment]
I'm using CRA and just added react-flexbox-grid to my project. I see CSS loading and columns working. My classes are very different from WeeJeWel's though (.row > .col-xs-12 .col-md-2), maybe because of an update.

react-flexbox-grid 1.1.5
create-react-app 1.4.0

**Comment by danny-andrews** [comment]
@WeeJeWel, @breakingthebuild Have you tried this with v1.1.5?

**Comment by breakingthebuild** [comment]
@danny-andrews It is working now. Thanks!
