### ISSUE TITLE
Get rid of changing config of library users.

### ISSUE THREAD

**Issue by IRus** [roylee0704/react-flexbox-grid#58]
Hi! Changing users config to support certain library very uncommon practice. 

Can we get rid of that?

**Comment by silvenon** [comment]
Do you mean because of CSS Modules?

**Comment by IRus** [comment]
@silvenon yep, sure

**Comment by silvenon** [comment]
With merging #90 I don't think this is an issue anymore (once it gets published, that is). You will be able to use CSS Modules, but you won't have to.

If you had a better solution in mind, I'll gladly reopen this.

**Comment by IRus** [comment]
LGTM, thanks!
