### ISSUE TITLE
Error in ./~/css-loader?modules!./~/style-loader!./~/flexboxgrid/dist/flexboxgrid.css

### ISSUE THREAD

**Issue by aindong** [roylee0704/react-flexbox-grid#59]
Hello guys,

I've been having trouble with including flexboxgrid with create-react-app of facebookincubator, I've already ejected from their settings and here's my loader:

`{
        test: /\.css$/,
        loader: 'style!css?modules',
        include: [
            /normalize\.css/,
            /flexboxgrid/
        ],
},`

<img width="927" alt="screen shot 2016-09-16 at 2 03 30 pm" src="https://cloud.githubusercontent.com/assets/1896053/18576698/820c5218-7c16-11e6-9cd7-0cfa31305b25.png">

**Comment by aindong** [comment]
I got the error, I also have a loader for postcss

`{
        test: /\.css$/,
        loader: 'style!css!postcss',
      },`

**Comment by tnegoshi** [comment]
Hey @aindong, I too was looking for compatibility with create-react-app tool and had ejected to edit the webpack.config files as per instructions

The relevant part of my loaders looks like this now to include react-flexbox-grid:

```
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader?modules=true',
        include: /flexboxgrid/
      },
      {
        test: /\.css$/,
        loader: 'style!css!postcss',
        include: path.join(__dirname, 'node_modules'),
        exclude: /flexboxgrid/ 
      },
```

This seems to build fine on a local server.

I was also having trouble getting this build to deploy on Heroku after ejecting from create-react-app tool. The solution to this was to make sure that when installing any dependencies to explicitly save them to production modules:

```
npm install classnames --save --prod
npm install flexboxgrid --save --prod
npm install react-flexbox-grid --save --prod
```

**Comment by amergin** [comment]
I'm also having this error when I try to add the provided configuration to my webpack config in my boilerplate setup. Specifically, how do I need to modify [this file](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L127) to make the setup work?

**Comment by meilers** [comment]
Having the same issue as @aindong and @amergin... also using postcss. I'm using [react boilerplate](https://github.com/mxstbr/react-boilerplate). Here's what I have as loaders in my webpack base config file (for css):

`    {
      test: /\.css$/,
      loader: 'style!css?modules',
      include: /flexboxgrid/,
    }, {
       // Transform our own .css files with PostCSS and CSS-modules
      test: /\.css$/,
      exclude: [/node_modules/,/flexboxgrid/],
      loader: ''style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader',
    }, {
      // Do not transform vendor's CSS with CSS-modules
      // The point is that they remain in global scope.
      // Since we require these CSS files in our JS or CSS files,
      // they will be a part of our compilation either way.
      // So, no need for ExtractTextPlugin here.
      test: /\.css$/,
      include: /node_modules/,
      exclude: /flexboxgrid/,
      loaders: ['style-loader', 'css-loader'],
    }, `

Here's the error:
"Dynamic page loading failed Error: Module build failed: Unknown word (5:1)"

![screen shot 2016-11-11 at 4 43 38 pm](https://cloud.githubusercontent.com/assets/2792041/20231188/0860a358-a82e-11e6-9f90-fe43455375b7.png)

This is for dev, not prod. I'm not using ExtractTextPlugin like @tnegoshi mentioned.

**Comment by amergin** [comment]
In the case you are using react-redux-starter, the working config is explained in [this comment](https://github.com/roylee0704/react-flexbox-grid/issues/24#issuecomment-252106892).

**Comment by silvenon** [comment]
I'm aware how horrendously late this reply is, 😓 but this issue happens most often because you have multiple loaders affecting same files. Check your `webpack.config.js` for possibly overlapping loaders.

All of you still experiencing this issue can paste their `webpack.config.js` (**all** of it) and I'll be happy to take a look.

I'm closing this because it's an issue with webpack configuration, not with react-flexbox-grid.
