### ISSUE TITLE
Module not found: Error: ?

### ISSUE THREAD

**Issue by mikedizon** [roylee0704/react-flexbox-grid#6]
ERROR in ./~/react-flexbox-grid/lib/components/Row.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../style in /Users/xxx/Code/G5/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Row.js 21:13-32

**Comment by roylee0704** [comment]
github.com/roylee0704#1

**Comment by roylee0704** [comment]
Have you check if solution at #2  works for you? :)

**Comment by roylee0704** [comment]
Hi @mikedizon I'm sorry for the late response, to address that issue, I have made an example repo just to show how to use `react-flexbox-grid` in webpack, sass, and css-modules.

You may pull from here: https://github.com/roylee0704/react-flexbox-grid-example :)

**Comment by mikedizon** [comment]
Thanks man, I'll check it out shortly. Was pulled into a different project
this week

On Thursday, January 21, 2016, LEE SIONG TAI (Roy) <notifications@github.com>
wrote:

> Hi @mikedizon <https://github.com/mikedizon> I'm sorry for the late
> response, to address that issue, I have made an example repo just to show
> how to use react-flexbox-grid in webpack, sass, and css-modules.
>
> You may pull from here:
> https://github.com/roylee0704/react-flexbox-grid-example :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roylee0704/react-flexbox-grid/issues/6#issuecomment-173469317>
> .
>


-- 
Sent from Gmail Mobile

**Comment by roylee0704** [comment]
Alright, feel free to reopen this issue if you still encounter any problem. :)
