### ISSUE TITLE
Make CSS Modules optional

### ISSUE THREAD

**Issue by djensen47** [roylee0704/react-flexbox-grid#60]
CSS Modules are great except when you don't want to use them. It was a thoughtful consideration to to use it in this project but I'd like to be able to turn it off as well.

**Comment by jhabdas** [comment]
I'm just pumped this library works with [Aphrodite](https://github.com/Khan/aphrodite). Great work! CSS Modules are the way to go. I'd wager one of the forks created is or will address the OPs concern.

**Comment by patrickml** [comment]
@jhabdas here is a 100% js solution using Aphrodite. https://github.com/patrickml/react-flexbox-grid-aphrodite

**Comment by silvenon** [comment]
Fixed in #90.
