### ISSUE TITLE
Alignment properties not working on Row component

### ISSUE THREAD

**Issue by bretthayes** [roylee0704/react-flexbox-grid#63]
It seems that the Row component only aligns children if you specify a height on the row.

Here's an example:

``` jsx
<Row middle="xs" style={{height: '100%'}}>
  <Col xs={3} />
  <Col xs={9} />
</Row>
```

I feel like this should be handled by the library itself. If it is necessary, maybe including a property of `fullHeight` for the Row component would help.

Any ideas why I have to do this manually?

**Comment by nfatah** [comment]
I also have a problem with the middle prop. It does not work at all.
The `center="xs"` works  even without specifying height.

**Comment by silvenon** [comment]
This library is meant to just be a wrapper around [flexboxgrid](http://flexboxgrid.com/), not really extend it. What if you want the row height to be exactly `520px`? Then you'd need to do that manually as well. We don't know the details of your usage, additional styling can be solved either via inline styles or through `className`.

`<Row middle="xs">` **does** align the columns at the middle as advertised, the columns have to be different heights for that to be visible. It just doesn't vertically stretch the row, which might not always be what you want.

**Comment by advance512** [comment]
What is the correct method of stretching all columns to be the same size inside a row?

```
<Grid fluid>
   <Row>
          <Col xs={12} sm={6} md={6} lg={4} style={colStyle}>
            {content.shift()}
          </Col>
          <Col xs={12} sm={6} md={6} lg={4} style={colStyle}>
            {content.shift()}
          </Col>
          <Col xs={12} sm={6} md={6} lg={4} style={colStyle}>
            {content.shift()}
          </Col>
        </Row>
</Grid>
```

I get columns with varying heights.

**Comment by advance512** [comment]
I realized the issue is the content, not the Col.

Check this out:
https://github.com/kristoferjoseph/flexboxgrid/issues/40
