### ISSUE TITLE
Error On install 

### ISSUE THREAD

**Issue by superchangme** [roylee0704/react-flexbox-grid#69]
when i npm install react-flexbox-grid
There is mistake as below :+1: 
![image](https://cloud.githubusercontent.com/assets/7008154/19550551/8fe13d46-96dc-11e6-8eba-23e0920969a3.png)
How can i deal with it?

**Comment by adambarthelson** [comment]
@superchangme Looks like you need to use admin or root permissions when running the command.  Your Node requires admin privileges.

**Comment by silvenon** [comment]
This is not an issue with react-flexbox-grid, so I'm closing this.
