### ISSUE TITLE
Isomorphic support 

### ISSUE THREAD

**Issue by Extra-lightwill** [roylee0704/react-flexbox-grid#80]
This looks like a great library and I'd love it to integrate into my project. 

However, I'm using an Isomorphic boilerplate (https://github.com/codefoundries/UniversalRelayBoilerplate) and I'm getting this error: 

```
 (function (exports, require, module, __filename, __dirname) { .container-fluid,
 SyntaxError: Unexpected token .
```

I realise that this has been brought up before but I don't feel like the referenced thread ('Note: If you need isomorphic support see https://github.com/roylee0704/react-flexbox-grid/issues/28#issuecomment-198758253.') gives an adequate or definitive answer on how to solve the problem. 

If anyone has made any progress on this since, I'd be very interested to hear how you managed to solve the issue.

**Comment by benbarber** [comment]
@Extra-lightwill I'm having the same issue when compiling for Node, did you resolve your issue?

**Comment by Extra-lightwill** [comment]
@benbarber Nope, didn't manage to resolve.

**Comment by mschipperheyn** [comment]
Also struggling with this: https://github.com/ctrlplusb/react-universally/issues

**Comment by mschipperheyn** [comment]
https://github.com/LoicMahieu/react-styled-flexboxgrid I found this similar library that uses styled-components which bypasses this whole issue.

**Comment by francoiscabrol** [comment]
I tried to use flexboxgrid.css directly in my code and I got the same error.
I have added the flexboxgrid dependency, then I tried to add `import flexbox from 'flexboxgrid';` in a .jsx component and I got the same
```
(function (exports, require, module, __filename, __dirname) { .container-fluid,
                                                             ^
SyntaxError: Unexpected token .
```

**Comment by francoiscabrol** [comment]
The error disappears if I use `import flexbox from 'flexboxgrid/dist/flexboxgrid.css';`

**Comment by azmum** [comment]
@francoiscabrol where do you use that import? on webpack entry file? Thank you

**Comment by roylee0704** [comment]
This should be fixed under v1.1.4.

**Comment by tgdn** [comment]
Still getting the issue in v1.1.5

**Comment by tgdn** [comment]
[react-styled-flexboxgrid](https://github.com/LoicMahieu/react-styled-flexboxgrid) works out of the box 👍

**Comment by danny-andrews** [comment]
You have to use `css-modules-require-hook`. See [this commit](https://github.com/danny-andrews/react-redux-universal-hot-example/commit/16087c787a802ea9a0410f99a06ae1481dbe1f94) for example usage.

**Comment by michaelroevievictoria** [comment]
Can anyone help me import the react-flexbox-grid? 

I have also isomorphic-style-loader.
this code i added to my webpack.config.
  ```
{
  test: reStyle,
  rules: [
    // Convert CSS into JS module
    {
      issuer: { not: [reStyle] },
      use: 'isomorphic-style-loader',
    },
    // flexbox edit
    {
      test: /\.css$/,
      loader: 'style-loader!css-loader!postcss-loader',
      include: path.join(__dirname, 'node_modules'), // oops, this also includes flexboxgrid
      exclude: /flexboxgrid/ // so we have to exclude it
    },
    // End
  ],
}
```

and i get the error TypeError: action.default is not a function, could anyone help me with my problem I also try different types of solution regarding with the css loader

[Here](https://github.com/roylee0704/react-flexbox-grid/issues/12)
and [this](https://github.com/roylee0704/react-flexbox-grid/issues/28)
