### ISSUE TITLE
Use with create-react-app

### ISSUE THREAD

**Issue by raitucarp** [roylee0704/react-flexbox-grid#85]
As stated here https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md

```
You may create subdirectories inside src. For faster rebuilds, only files inside src are processed by Webpack.
You need to put any JS and CSS files inside src, or Webpack won’t see them.
```

Can I use react-flexbox-grid with that flow? Because including webpack in src folder will be redundant (CMIIW).

Thanks

**Comment by cristianocca** [comment]
Any news? I need this aswell and doesn't seem to be working right away simply with npm install and demo code.

**Comment by arronhunt** [comment]
Bumping this one

**Comment by silvenon** [comment]
Hello! Sorry for the delay. react-flexbox-grid currently relies on CSS Modules, which CRA doesn't support AFAIK (it doesn't let you customize the CSS webpack loader).

We should make react-flexbox-grid somehow work both with CSS Modules and without them. I'll investigate this today, please subscribe to #60 for updates.

**Comment by deltaidea** [comment]
I don't know how long it is until 1.0.0, so for now see https://github.com/roylee0704/react-flexbox-grid/issues/55#issuecomment-285555262
