### ISSUE TITLE
ExtractTextPlugin doesn't import classes

### ISSUE THREAD

**Issue by h0x539** [roylee0704/react-flexbox-grid#88]
Hi!

Does anybody had the problem with CSS classes which are not imported from dist/flexboxgrid.css ?

I'm using: 
-  "extract-text-webpack-plugin": "^2.0.0-rc.3",
-  "webpack": "^2.2.1"

`
plugins: [
  new ExtractTextPlugin("styles.css")
]
`

`{
      test: /\.css$/,
      use: ExtractTextPlugin.extract({
        fallback: "style-loader",
        use: "css-loader"
      }),
      include: /flexboxgrid/,
    }`

Thanks!

**Comment by silvenon** [comment]
Have you tried enabling [CSS Modules](https://github.com/webpack-contrib/css-loader#css-modules)? `use: "css-loader?modules"`

**Comment by h0x539** [comment]
@silvenon I solved this problem, I'm sorry, I forgot to update this issue. I had a problem with a npm library at compilation. 

This issue can be closed / deleted.

Thanks for your response!
