### ISSUE TITLE
Flexboxgrid example

### ISSUE THREAD

**Issue by ansonla3** [roylee0704/react-flexbox-grid#9]
could you list out some examples to demonstrate the responsive layout ? I do not know what it does in the http://roylee0704.github.io/react-flexbox-grid/  responsive example. I have knowledge on bootstrap grid system & materializecss responsive layout, but this one seems lack of explanation. Many thanks.

**Comment by roylee0704** [comment]
Hey @ansonla3 :) Meanwhile, the source for the example can be found here: https://github.com/roylee0704/react-flexbox-grid/tree/master/doc

**Comment by roylee0704** [comment]
Okay, I have finally completed the example to `react-flexbox-grid`, which you can pull it from here: https://github.com/roylee0704/react-flexbox-grid-example

**Comment by roylee0704** [comment]
@ansola3 , you may reopen this if you think that example doesn't help. :)
