### ISSUE TITLE
Module not found: Error: Can't resolve 'flexboxgrid'

### ISSUE THREAD

**Issue by mschipperheyn** [roylee0704/react-flexbox-grid#92]
I assume bc it's listed as a dev dependency in package.json.

	Module not found: Error: Can't resolve 'flexboxgrid' in '[..]/react/projects/MobileMinds/node_modules/react-flexbox-grid/lib/components'
	 @ ./~/react-flexbox-grid/lib/components/Grid.js 18:19-41
	 @ ./~/react-flexbox-grid/lib/index.js

Same goes for classnames

**Comment by silvenon** [comment]
Assuming you're using v0.10.2, those are listed as **peer** dependencies, meaning you have to install them yourself. We already moved away from that, but haven't released a new version in forever. I'm working on cleaning up existing bugs and we'll hopefully release soon.
