### ISSUE TITLE
the container has no padding, resulting to nonresponsive

### ISSUE THREAD

**Issue by farzer** [roylee0704/react-flexbox-grid#96]
![image](https://cloud.githubusercontent.com/assets/9881593/23443993/64695d58-fe6d-11e6-8e2f-531ec76b69c6.png)

container just only has `margin`, but row has `margin-left: -0.5em` and `margin-right: -0.5em`

or something wrong i made?

**Comment by silvenon** [comment]
`<Grid>` will become `.container`, `<Grid fluid>` will become `.container-fluid`. Look at [flexboxgrid.css](https://github.com/kristoferjoseph/flexboxgrid/blob/140537b370f7dcef1d357ac82344627a1e1a2107/src/css/flexboxgrid.css) to see what that means.
