### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by hourliert** [roylee0704/react-flexbox-grid#99]
Hi,

Thanks for this great library.

I have seen that no release has been made since July 2016. Are you planing to release a new version soon? 
My team needs some codes that has been merged into master recently.

Thanks in advance!

**Comment by deltaidea** [comment]
See last comments on #55. TL;DR:
- author has been sick, he's ok and a we'll probably see a release soon;
- use `master` directly for now to use latest features until 1.0.0 gets released.

**Comment by silvenon** [comment]
I sent a [tweet](https://twitter.com/silvenon/status/842711607423721473) just now, hopefully I'll get a reply. Thanks for being patient. 😉

**Comment by hourliert** [comment]
Thanks a lot for your answers. I hope the author is alright.

**Comment by silvenon** [comment]
I was just double-checking where I read that he was sick (that memory was from a while ago), but I can't find it, maybe I got him confused with someone else. Anyway, sick or not sick, people have a lot of things going on in their lives, the most loving thing we can do is use `master`. 😜

**Comment by roylee0704** [comment]
@hourliert It's done! :)

@deltaidea thanks for guiding the rest to use `master` branch, you're awesome  :)

@silvenon Thank you so much for helping me to maintain the repo all these while. You know what, you're super awesome, I wish I could give you a big hug :)

**Comment by roylee0704** [comment]
Closing issue, the new release is completed.

**Comment by hourliert** [comment]
Thanks a lot!!!
